#! /usr/bin/env python

import os
from os.path import expanduser
import sys
import subprocess as sp
import argparse
import shlex
import cli
import re
import errno 
import signal
from getpass import getpass
import itertools
import ConfigParser

UNLOSETUP = '/sbin/losetup -d %s'
CRYPTSETUP = '/sbin/cryptsetup -T 1 -d - luksOpen %s %s'
UNCRYPTSETUP = '/sbin/cryptsetup luksClose %s'
MHELP = "mount FILE's filesystem"
WHELP = "mount filesystem read/write"
UHELP = "umount filesystem from MOUNTPOINT"
CHELP = "create SIZE MB filesystem in FILE"

class ExecError(Exception):
    pass

class CryptError(Exception):
    pass

def mkmp(basefile, loopdev):
    mp = '/media/%s' % basefile
    try:
        # Create a mount point
        os.mkdir(mp)
    except OSError, e:
        print >>sys.stderr, '[mkdir] %s: %s' % (e.strerror, e.filename)
        try:
            # Device-unmap loop device
            ex(UNCRYPTSETUP % basefile)

            # Detach loop device
            ex(UNLOSETUP % loopdev)
        except ExecError, e:
            print >>sys.stderr, e

        raise CryptError

    return mp

def mntfs(basefile, loopdev, mp, read_write=False):
    try:
        # Mount the now decrypted file system
        ro = '' if read_write else '-r'
        ex('/bin/mount %s /dev/mapper/%s %s' % (ro, basefile, mp))
    except ExecError, e:
        print >>sys.stderr, e
        try:
            # Remove mount point
            os.rmdir(mp)

            # Device-unmap loop device
            ex(UNCRYPTSETUP % basefile)

            # Detach loop device
            ex(UNLOSETUP % loopdev)
        except ExecError, e:
            print >>sys.stderr, e
        except OSError, e:
            print >>sys.stderr, '[rmdir] %s: %s' % (e.strerror, e.filename)

        raise CryptError

def losetup(path):
    try:
        # Find first unused loop device
        loopdev, _ = ex('/sbin/losetup -f')

        # Attach loop device
        ex('/sbin/losetup %s %s' % (loopdev, path))
    except ExecError, e:
        print >>sys.stderr, e
        raise CryptError

    return loopdev

class Mnt(cli.Cli):
    def __init__(self, timeout):
        cli.Cli.__init__(self)

        self.timeout = timeout

        self.mountparser.add_argument(metavar='FILE', dest='files', nargs='+')
        self.mountparser.add_argument('-w', '--read-write', action='store_true',
                                      help=WHELP)
        self.mountparser.description = MHELP

        self.umountparser.add_argument(metavar='MOUNTPOINT', dest='mountpoints',
                                       nargs='+')
        self.umountparser.description = UHELP

        self.createparser.add_argument(metavar='FILE', dest='filepath')
        self.createparser.add_argument('-s', '--size', type=int)
        self.createparser.description = CHELP

        self.passphrase = None
        signal.signal(signal.SIGALRM, self.handler)

    def handler(self, signum, frame):
        self.passphrase = None

    def run_mount(self, args):
        self.passphrase = mount(args, self.passphrase)
        signal.alarm(self.timeout) # Forget passphrase after some time

    def run_umount(self, args):
        umount(args)

    def run_create(self, args):
        self.passphrase = create(args, self.passphrase)
        signal.alarm(60 * 60) # Forget passphrase after 1 hour

def ex(cmd, input=None):
    args = shlex.split(cmd)
    try:
        p = sp.Popen(args, stdin=sp.PIPE, stdout=sp.PIPE, stderr=sp.PIPE)
    except KeyboardInterrupt:
        return
    stdout, stderr = p.communicate(input)
    if p.returncode != 0:
        out = stderr if len(stderr) > 0 else stdout
        raise ExecError('[%s] %s' % (os.path.basename(args[0]), out[:-1]))
    return stdout, stderr

def mount(args, passphrase=None):
    for i, f in enumerate([expanduser(f) for f in args.files]):
        # Set unique basefile 
        basefile = os.path.basename(os.path.abspath(f))
        j, suffix = 0, ''
        while os.path.isdir('/media/%s%s' % (basefile, suffix)):
            suffix = str(j)
            j += 1
        basefile = basefile + suffix

        try:
            loopdev = losetup(f)
        except CryptError:
            return

        try:
            # Prompt and store passphrase
            if not passphrase:
                passphrase = getpass('Enter passphrase for %s: ' % basefile)

            # Device-map loop device
            ex(CRYPTSETUP % (loopdev, basefile), passphrase)
        except ExecError, e:
            print >>sys.stderr, e
            try:
                # Detach loop device
                ex(UNLOSETUP % loopdev)
            except:
                print >>sys.stderr, e
            return
        except KeyboardInterrupt:
            try:
                # Detach loop device
                ex(UNLOSETUP % loopdev)
            except ExecError, e:
                print >>sys.stderr, e
            print
            return

        try:
            mp = mkmp(basefile, loopdev)
        except CryptError:
            return

        try:
            mntfs(basefile, loopdev, mp, args.read_write)
        except CryptError:
            return

    return passphrase

def umount(args):
    for f in args.mountpoints:
        basefile = os.path.basename(os.path.abspath(f))

        # Find out which loop device we're dealing with
        try:
            stdout, _ = ex('/sbin/cryptsetup status %s' % basefile)
        except ExecError, e:
            print >>sys.stderr, e
            return 1
        r = re.compile('.*  device:  (?P<loopdev>/dev/loop\d+).*', re.S)
        m = r.match(stdout)
        if m is not None:
            loopdev = m.group('loopdev')
        else:
            msg = "No loop device seems to be mapped to %s"
            print >>sys.stderr, msg % basefile
            return 1

        try:
            # Umount file system
            ex('/bin/umount %s' % f)
        except ExecError, e:
            print >>sys.stderr, e
            return 1

        # Remove mount point
        try:
            os.rmdir(f)
        except OSError, e:
            print >>sys.stderr, '[rmdir] %s: %s' % (e.strerror, e.filename)
            return 1

        try:
            # Device-unmap loop device
            ex(UNCRYPTSETUP % basefile)
        except ExecError, e:
            print >>sys.stderr, e
            return 1

        try:
            # Detach loop device
            ex(UNLOSETUP % loopdev)
        except ExecError, e:
            print >>sys.stderr, e
            return 1

def create(args, passphrase=None):
    try:
        # Fill new file with random data
        ex('/bin/dd if=/dev/urandom of=%s bs=1M count=%d' % \
            (args.filepath, args.size))
    except ExecError, e:
        print >>sys.stderr, e
        return

    try:
        loopdev = losetup(args.filepath)
    except CryptError:
        return

    basefile = os.path.basename(os.path.abspath(args.filepath))

    try:
        # Prompt and store passphrase
        if not passphrase:
            passphrase = getpass('Enter passphrase for %s: ' % basefile)

        # Initialise LUKS partition
        ex('/sbin/cryptsetup -d - luksFormat %s' % loopdev, passphrase)

        # Device-map loop device
        ex(CRYPTSETUP % (loopdev, basefile), passphrase)
    except (KeyboardInterrupt, ExecError), e:
        if isinstance(e, ExecError): 
            print >>sys.stderr, e
        try:
            # Detach loop device
            ex(UNLOSETUP % loopdev)
        except ExecError, e:
            print >>sys.stderr, e

        return

    try:
        # Make filesystem
        ex('/sbin/mkfs.ext2 /dev/mapper/%s' % basefile)
    except ExecError, e:
        print >>sys.stderr, e
        
        try:
            # Device-unmap loop device
            ex(UNCRYPTSETUP % basefile)

            # Detach loop device
            ex(UNLOSETUP % loopdev)
        except ExecError, e:
            print >>sys.stderr, e
        
        return

    try:
        mp = mkmp(basefile, loopdev)
    except CryptError:
        return

    try:
        mntfs(basefile, loopdev, mp)
    except CryptError:
        return

    return passphrase

def main():
    # Config
    config = ConfigParser.SafeConfigParser()
    config.read(expanduser('~/.mnt.cfg'))
    try:
        timeout = config.getint('security', 'timeout')
    except (ConfigParser.NoSectionError, ConfigParser.NoOptionError):
        timeout = 43200

    # Arguments
    if len(sys.argv) > 1:
        parser = argparse.ArgumentParser()
        subs = parser.add_subparsers()

        mountparser = subs.add_parser('mount', help=MHELP)
        mountparser.add_argument(metavar='FILE', dest='files', nargs='+')
        mountparser.add_argument('-w', '--read-write', action='store_true',
                                 help=WHELP)
        mountparser.set_defaults(func=mount)

        umountparser = subs.add_parser('umount', help=UHELP)
        umountparser.add_argument(metavar='MOUNTPOINT', dest='mountpoints',
                                  nargs='+')
        umountparser.set_defaults(func=umount)

        createparser = subs.add_parser('create', help=CHELP)
        createparser.add_argument(metavar='FILE', dest='filepath')
        createparser.add_argument('-s', '--size', type=int)
        createparser.set_defaults(func=create)

        args = parser.parse_args()

        args.func(args)
    else:
        Mnt(timeout).loop()

if __name__ == '__main__':
    sys.exit(main())
